package com.divitiae.pulsesync.data.auth

import android.content.Context
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions

/**
 * Builds the Google Sign-In client used to obtain a Google ID token, which
 * [AuthRepository] then exchanges through Firebase for a PulseSync JWT.
 *
 * TODO(team): once google-services.json is added, pass
 * getString(R.string.default_web_client_id) as [webClientId] — that resource
 * is generated by the google-services plugin and must not be hard-coded.
 */
object GoogleSignInHelper {

    /** Placeholder until Firebase is provisioned; replace via the resource above. */
    const val PLACEHOLDER_WEB_CLIENT_ID = "REPLACE_WITH_DEFAULT_WEB_CLIENT_ID"

    fun client(context: Context, webClientId: String): GoogleSignInClient {
        val options = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(webClientId)
            .requestEmail()
            .build()
        return GoogleSignIn.getClient(context, options)
    }
}
