package com.divitiae.pulsesync.data.auth

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM encryption backed by the Android Keystore. The key never leaves
 * the secure hardware (or the TEE-backed keystore on devices without a
 * StrongBox), so a JWT written to disk cannot be read by another app or by
 * pulling the DataStore file off a rooted device.
 *
 * Output format: Base64( IV[12 bytes] || ciphertext+tag ). The IV is random per
 * encryption, which GCM requires for safety.
 *
 * This exists so the app has zero extra dependencies: Jetpack's
 * `security-crypto` / EncryptedSharedPreferences is deprecated by Google.
 */
class TokenCipher(private val alias: String = DEFAULT_ALIAS) {

    private val keyStore: KeyStore by lazy {
        KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
    }

    fun encrypt(plainText: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val iv = cipher.iv // 12-byte random IV generated by the keystore
        val cipherText = cipher.doFinal(plainText.toByteArray(Charsets.UTF_8))
        return Base64.encodeToString(iv + cipherText, Base64.NO_WRAP)
    }

    /**
     * Returns null instead of throwing when the payload is corrupt or the key
     * was rotated/invalidated (e.g. the user removed their lock screen with an
     * auth-bound key). Callers treat null as "signed out".
     */
    fun decrypt(encoded: String): String? = try {
        val bytes = Base64.decode(encoded, Base64.NO_WRAP)
        if (bytes.size <= IV_LENGTH_BYTES) return null
        val iv = bytes.copyOfRange(0, IV_LENGTH_BYTES)
        val cipherText = bytes.copyOfRange(IV_LENGTH_BYTES, bytes.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(TAG_LENGTH_BITS, iv))
        String(cipher.doFinal(cipherText), Charsets.UTF_8)
    } catch (_: Exception) {
        null
    }

    private fun getOrCreateKey(): SecretKey {
        (keyStore.getKey(alias, null) as? SecretKey)?.let { return it }
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        val spec = KeyGenParameterSpec.Builder(
            alias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )